/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
If you want to view the source, please visit the GitHub repository of this plugin.
*/

"use strict";
var __defProp = Object.defineProperty;
var __getOwnPropDesc = Object.getOwnPropertyDescriptor;
var __getOwnPropNames = Object.getOwnPropertyNames;
var __hasOwnProp = Object.prototype.hasOwnProperty;
var __export = (target, all) => {
  for (var name in all)
    __defProp(target, name, { get: all[name], enumerable: true });
};
var __copyProps = (to, from, except, desc) => {
  if (from && typeof from === "object" || typeof from === "function") {
    for (let key of __getOwnPropNames(from))
      if (!__hasOwnProp.call(to, key) && key !== except)
        __defProp(to, key, { get: () => from[key], enumerable: !(desc = __getOwnPropDesc(from, key)) || desc.enumerable });
  }
  return to;
};
var __toCommonJS = (mod) => __copyProps(__defProp({}, "__esModule", { value: true }), mod);

// src/main.ts
var main_exports = {};
__export(main_exports, {
  default: () => PreachMDPlugin
});
module.exports = __toCommonJS(main_exports);
var import_obsidian4 = require("obsidian");

// src/preach-view.ts
var import_obsidian2 = require("obsidian");

// src/timer.ts
var PreachTimer = class {
  constructor(container, thresholds) {
    // Three-state machine
    this.runState = "idle";
    // Timestamp when the current running segment began
    this.segmentStart = null;
    this.intervalId = null;
    // Double-tap detection
    this.lastTapTime = 0;
    this.singleTapTimeout = null;
    this.thresholds = thresholds;
    this.remainingAtPause = thresholds.targetMinutes * 60;
    this.el = container.createEl("div", { cls: "preach-timer" });
    this.el.setAttribute("role", "timer");
    this.el.setAttribute("aria-live", "off");
    this.el.dataset.runState = "idle";
    this.labelEl = container.createEl("div", { cls: "preach-timer-label" });
    this.labelEl.textContent = "Start";
    this.el.addEventListener("pointerdown", (e) => {
      e.stopPropagation();
      this.handleTap();
    });
    this.renderDisplay();
  }
  // Called from preach-view after open - starts tick loop so display is live
  start() {
    this.renderDisplay();
  }
  stop() {
    this.clearInterval();
    if (this.singleTapTimeout !== null) {
      window.clearTimeout(this.singleTapTimeout);
      this.singleTapTimeout = null;
    }
  }
  updateThresholds(thresholds) {
    this.thresholds = thresholds;
    if (this.runState === "idle") {
      this.remainingAtPause = thresholds.targetMinutes * 60;
    }
    this.renderDisplay();
  }
  // Single tap: toggle running/paused (or start if idle)
  // Double tap (within 300ms): reset to idle
  handleTap() {
    const now = Date.now();
    const timeSinceLast = now - this.lastTapTime;
    this.lastTapTime = now;
    if (timeSinceLast < 300) {
      if (this.singleTapTimeout !== null) {
        window.clearTimeout(this.singleTapTimeout);
        this.singleTapTimeout = null;
      }
      this.transitionToIdle();
      return;
    }
    this.singleTapTimeout = window.setTimeout(() => {
      this.singleTapTimeout = null;
      this.handleSingleTap();
    }, 300);
  }
  handleSingleTap() {
    if (this.runState === "idle" || this.runState === "paused") {
      this.transitionToRunning();
    } else {
      this.transitionToPaused();
    }
  }
  transitionToRunning() {
    this.segmentStart = Date.now();
    this.runState = "running";
    this.el.dataset.runState = "running";
    this.intervalId = window.setInterval(() => this.tick(), 250);
    this.tick();
  }
  transitionToPaused() {
    this.remainingAtPause = this.computeRemaining();
    this.clearInterval();
    this.segmentStart = null;
    this.runState = "paused";
    this.el.dataset.runState = "paused";
    this.renderDisplay();
  }
  transitionToIdle() {
    this.clearInterval();
    this.segmentStart = null;
    this.runState = "idle";
    this.el.dataset.runState = "idle";
    this.remainingAtPause = this.thresholds.targetMinutes * 60;
    this.renderDisplay();
  }
  clearInterval() {
    if (this.intervalId !== null) {
      window.clearInterval(this.intervalId);
      this.intervalId = null;
    }
  }
  computeRemaining() {
    if (this.segmentStart === null)
      return this.remainingAtPause;
    const elapsed = (Date.now() - this.segmentStart) / 1e3;
    return this.remainingAtPause - elapsed;
  }
  tick() {
    this.renderDisplay();
  }
  renderDisplay() {
    const remaining = this.runState === "running" ? this.computeRemaining() : this.remainingAtPause;
    const isOvertime = remaining < 0;
    const absSecs = Math.abs(Math.ceil(remaining));
    const mins = Math.floor(absSecs / 60);
    const secs = absSecs % 60;
    const timeStr = `${mins}:${secs.toString().padStart(2, "0")}`;
    const display = isOvertime ? `+${timeStr}` : timeStr;
    this.el.textContent = display;
    const remainingMins = remaining / 60;
    let colourState;
    if (isOvertime) {
      colourState = "overtime";
    } else if (remainingMins <= this.thresholds.critMinutes) {
      colourState = "crit";
    } else if (remainingMins <= this.thresholds.warnMinutes) {
      colourState = "warn";
    } else {
      colourState = "normal";
    }
    this.el.dataset.state = colourState;
    if (this.runState === "idle") {
      this.labelEl.textContent = "Start";
    } else if (this.runState === "running") {
      this.labelEl.textContent = "Pause";
    } else {
      this.labelEl.textContent = "Resume | reset";
    }
  }
};

// src/highlight.ts
function parseBlocks(markdown) {
  const blocks = [];
  let bodyStart = 0;
  if (markdown.startsWith("---")) {
    const end = markdown.indexOf("\n---", 3);
    if (end !== -1) {
      bodyStart = end + 4;
      if (markdown[bodyStart] === "\n")
        bodyStart++;
    }
  }
  const body = markdown.slice(bodyStart);
  let inCodeFence = false;
  const lines = body.split("\n");
  let i = 0;
  let charOffset = bodyStart;
  while (i < lines.length) {
    const line = lines[i];
    if (/^```/.test(line) || /^~~~/.test(line)) {
      inCodeFence = !inCodeFence;
    }
    if (inCodeFence || line.trim() === "") {
      charOffset += line.length + 1;
      i++;
      continue;
    }
    const blockStartOffset = charOffset;
    const blockLines = [];
    let inFence = inCodeFence;
    while (i < lines.length && lines[i].trim() !== "") {
      if (/^```/.test(lines[i]) || /^~~~/.test(lines[i])) {
        inFence = !inFence;
      }
      blockLines.push(lines[i]);
      charOffset += lines[i].length + 1;
      i++;
    }
    const blockText = blockLines.join("\n");
    const blockEnd = charOffset;
    const firstLine = blockLines[0];
    const isHeading = /^#{1,6}\s/.test(firstLine);
    const isHr = /^(\*{3,}|-{3,}|_{3,})\s*$/.test(firstLine);
    const isCodeFenceBlock = /^```|^~~~/.test(firstLine);
    const isBlockquote = /^>/.test(firstLine);
    const isList = /^[-*+]\s|^\d+[.)]\s/.test(firstLine);
    const isCallout = /^>\s*\[!/.test(firstLine);
    const highlightable = !isHeading && !isHr && !isCodeFenceBlock && !isBlockquote && !isList && !isCallout && blockText.trim().length > 0;
    blocks.push({
      start: blockStartOffset,
      end: blockEnd,
      content: blockText,
      highlightable
    });
  }
  return blocks;
}
function toggleHighlight(content) {
  const trimmed = content.trim();
  if (trimmed.startsWith("==") && trimmed.endsWith("==") && trimmed.length > 4) {
    return content.replace(/==/g, "");
  }
  const leadMatch = content.match(/^(\s*)/);
  const trailMatch = content.match(/(\s*)$/);
  const lead = leadMatch ? leadMatch[1] : "";
  const trail = trailMatch ? trailMatch[1] : "";
  const inner = content.slice(lead.length, content.length - trail.length);
  return `${lead}==${inner}==${trail}`;
}
var HighlightManager = class {
  constructor(app, file, renderComponent) {
    this.blocks = [];
    this.active = false;
    this.btn = null;
    this.app = app;
    this.file = file;
    this.renderComponent = renderComponent;
  }
  /** Call once after the preach view is built to wire the button and content area. */
  init(btn, scrollEl, bodyEl) {
    this.btn = btn;
    this.scrollEl = scrollEl;
    this.bodyEl = bodyEl;
    this.updateButtonState();
  }
  updateFile(file) {
    this.file = file;
  }
  isActive() {
    return this.active;
  }
  toggle() {
    this.active = !this.active;
    this.updateButtonState();
  }
  /**
   * Called after the preach view renders a new file.
   * Rebuilds block map and attaches tap listeners to block wrappers.
   */
  attachBlocks(blocks) {
    this.blocks = blocks;
  }
  /**
   * Handle a tap on a block element. If highlight mode is on and the block
   * is highlightable, toggle ==...== in the source file and re-render the block.
   */
  async handleBlockTap(blockIndex) {
    if (!this.active)
      return;
    const block = this.blocks[blockIndex];
    if (!block || !block.highlightable || !this.file)
      return;
    const file = this.file;
    const scrollTop = this.scrollEl.scrollTop;
    await this.app.vault.process(file, (source) => {
      const before = source.slice(0, block.start);
      const content = source.slice(block.start, block.end);
      const after = source.slice(block.end);
      const toggled = toggleHighlight(content);
      block.content = toggled.trim();
      return before + toggled + after;
    });
    const updated = await this.app.vault.read(file);
    this.blocks = parseBlocks(updated);
    window.requestAnimationFrame(() => {
      this.scrollEl.scrollTop = scrollTop;
    });
  }
  updateButtonState() {
    if (!this.btn)
      return;
    if (this.active) {
      this.btn.classList.add("preach-highlight-btn--on");
      this.btn.setAttribute("aria-pressed", "true");
    } else {
      this.btn.classList.remove("preach-highlight-btn--on");
      this.btn.setAttribute("aria-pressed", "false");
    }
  }
};

// src/scripture.ts
var import_obsidian = require("obsidian");
var BOOK_MAP = {
  // Genesis
  genesis: "Genesis",
  gen: "Genesis",
  ge: "Genesis",
  gn: "Genesis",
  // Exodus
  exodus: "Exodus",
  exod: "Exodus",
  ex: "Exodus",
  exo: "Exodus",
  // Leviticus
  leviticus: "Leviticus",
  lev: "Leviticus",
  le: "Leviticus",
  lv: "Leviticus",
  // Numbers
  numbers: "Numbers",
  num: "Numbers",
  nu: "Numbers",
  nm: "Numbers",
  nb: "Numbers",
  // Deuteronomy
  deuteronomy: "Deuteronomy",
  deut: "Deuteronomy",
  dt: "Deuteronomy",
  deu: "Deuteronomy",
  // Joshua
  joshua: "Joshua",
  josh: "Joshua",
  jos: "Joshua",
  jsh: "Joshua",
  // Judges
  judges: "Judges",
  judg: "Judges",
  jdg: "Judges",
  jg: "Judges",
  jdgs: "Judges",
  // Ruth
  ruth: "Ruth",
  rut: "Ruth",
  ru: "Ruth",
  // 1 Samuel
  "1 samuel": "1 Samuel",
  "1samuel": "1 Samuel",
  "1sam": "1 Samuel",
  "1sa": "1 Samuel",
  "1s": "1 Samuel",
  "i samuel": "1 Samuel",
  "i sam": "1 Samuel",
  // 2 Samuel
  "2 samuel": "2 Samuel",
  "2samuel": "2 Samuel",
  "2sam": "2 Samuel",
  "2sa": "2 Samuel",
  "ii samuel": "2 Samuel",
  "ii sam": "2 Samuel",
  // 1 Kings
  "1 kings": "1 Kings",
  "1kings": "1 Kings",
  "1kgs": "1 Kings",
  "1ki": "1 Kings",
  "1kg": "1 Kings",
  "i kings": "1 Kings",
  // 2 Kings
  "2 kings": "2 Kings",
  "2kings": "2 Kings",
  "2kgs": "2 Kings",
  "2ki": "2 Kings",
  "ii kings": "2 Kings",
  // 1 Chronicles
  "1 chronicles": "1 Chronicles",
  "1chronicles": "1 Chronicles",
  "1chr": "1 Chronicles",
  "1ch": "1 Chronicles",
  "i chronicles": "1 Chronicles",
  // 2 Chronicles
  "2 chronicles": "2 Chronicles",
  "2chronicles": "2 Chronicles",
  "2chr": "2 Chronicles",
  "2ch": "2 Chronicles",
  "ii chronicles": "2 Chronicles",
  // Ezra
  ezra: "Ezra",
  ezr: "Ezra",
  // Nehemiah
  nehemiah: "Nehemiah",
  neh: "Nehemiah",
  ne: "Nehemiah",
  // Esther
  esther: "Esther",
  est: "Esther",
  esth: "Esther",
  // Job
  job: "Job",
  jb: "Job",
  // Psalms
  psalms: "Psalms",
  psalm: "Psalms",
  ps: "Psalms",
  psa: "Psalms",
  psm: "Psalms",
  pss: "Psalms",
  // Proverbs
  proverbs: "Proverbs",
  prov: "Proverbs",
  pr: "Proverbs",
  prv: "Proverbs",
  // Ecclesiastes
  ecclesiastes: "Ecclesiastes",
  eccl: "Ecclesiastes",
  ecc: "Ecclesiastes",
  ec: "Ecclesiastes",
  qoh: "Ecclesiastes",
  // Song of Solomon
  "song of solomon": "Song of Solomon",
  "song of songs": "Song of Solomon",
  "song": "Song of Solomon",
  sos: "Song of Solomon",
  ss: "Song of Solomon",
  cant: "Song of Solomon",
  // Isaiah
  isaiah: "Isaiah",
  isa: "Isaiah",
  is: "Isaiah",
  // Jeremiah
  jeremiah: "Jeremiah",
  jer: "Jeremiah",
  je: "Jeremiah",
  jr: "Jeremiah",
  // Lamentations
  lamentations: "Lamentations",
  lam: "Lamentations",
  la: "Lamentations",
  // Ezekiel
  ezekiel: "Ezekiel",
  ezek: "Ezekiel",
  eze: "Ezekiel",
  ezk: "Ezekiel",
  // Daniel
  daniel: "Daniel",
  dan: "Daniel",
  da: "Daniel",
  dn: "Daniel",
  // Hosea
  hosea: "Hosea",
  hos: "Hosea",
  ho: "Hosea",
  // Joel
  joel: "Joel",
  joe: "Joel",
  jl: "Joel",
  // Amos
  amos: "Amos",
  am: "Amos",
  // Obadiah
  obadiah: "Obadiah",
  obad: "Obadiah",
  ob: "Obadiah",
  // Jonah
  jonah: "Jonah",
  jon: "Jonah",
  jnh: "Jonah",
  // Micah
  micah: "Micah",
  mic: "Micah",
  mi: "Micah",
  // Nahum
  nahum: "Nahum",
  nah: "Nahum",
  na: "Nahum",
  // Habakkuk
  habakkuk: "Habakkuk",
  hab: "Habakkuk",
  // Zephaniah
  zephaniah: "Zephaniah",
  zeph: "Zephaniah",
  zep: "Zephaniah",
  zp: "Zephaniah",
  // Haggai
  haggai: "Haggai",
  hag: "Haggai",
  hg: "Haggai",
  // Zechariah
  zechariah: "Zechariah",
  zech: "Zechariah",
  zec: "Zechariah",
  zc: "Zechariah",
  // Malachi
  malachi: "Malachi",
  mal: "Malachi",
  ml: "Malachi",
  // Matthew
  matthew: "Matthew",
  matt: "Matthew",
  mat: "Matthew",
  mt: "Matthew",
  // Mark
  mark: "Mark",
  mrk: "Mark",
  mar: "Mark",
  mk: "Mark",
  mr: "Mark",
  // Luke
  luke: "Luke",
  luk: "Luke",
  lk: "Luke",
  // John
  john: "John",
  joh: "John",
  jn: "John",
  jhn: "John",
  // Acts
  acts: "Acts",
  act: "Acts",
  ac: "Acts",
  // Romans
  romans: "Romans",
  rom: "Romans",
  ro: "Romans",
  rm: "Romans",
  // 1 Corinthians
  "1 corinthians": "1 Corinthians",
  "1corinthians": "1 Corinthians",
  "1cor": "1 Corinthians",
  "1co": "1 Corinthians",
  "i corinthians": "1 Corinthians",
  "i cor": "1 Corinthians",
  "1 cor": "1 Corinthians",
  // 2 Corinthians
  "2 corinthians": "2 Corinthians",
  "2corinthians": "2 Corinthians",
  "2cor": "2 Corinthians",
  "2co": "2 Corinthians",
  "ii corinthians": "2 Corinthians",
  "ii cor": "2 Corinthians",
  "2 cor": "2 Corinthians",
  // Galatians
  galatians: "Galatians",
  gal: "Galatians",
  ga: "Galatians",
  // Ephesians
  ephesians: "Ephesians",
  eph: "Ephesians",
  // Philippians
  philippians: "Philippians",
  phil: "Philippians",
  php: "Philippians",
  pp: "Philippians",
  // Colossians
  colossians: "Colossians",
  col: "Colossians",
  // 1 Thessalonians
  "1 thessalonians": "1 Thessalonians",
  "1thessalonians": "1 Thessalonians",
  "1thess": "1 Thessalonians",
  "1th": "1 Thessalonians",
  "i thessalonians": "1 Thessalonians",
  "1 thess": "1 Thessalonians",
  // 2 Thessalonians
  "2 thessalonians": "2 Thessalonians",
  "2thessalonians": "2 Thessalonians",
  "2thess": "2 Thessalonians",
  "2th": "2 Thessalonians",
  "ii thessalonians": "2 Thessalonians",
  "2 thess": "2 Thessalonians",
  // 1 Timothy
  "1 timothy": "1 Timothy",
  "1timothy": "1 Timothy",
  "1tim": "1 Timothy",
  "1ti": "1 Timothy",
  "i timothy": "1 Timothy",
  "1 tim": "1 Timothy",
  // 2 Timothy
  "2 timothy": "2 Timothy",
  "2timothy": "2 Timothy",
  "2tim": "2 Timothy",
  "2ti": "2 Timothy",
  "ii timothy": "2 Timothy",
  "2 tim": "2 Timothy",
  // Titus
  titus: "Titus",
  tit: "Titus",
  ti: "Titus",
  // Philemon
  philemon: "Philemon",
  phlm: "Philemon",
  phm: "Philemon",
  // Hebrews
  hebrews: "Hebrews",
  heb: "Hebrews",
  // James
  james: "James",
  jas: "James",
  jm: "James",
  // 1 Peter
  "1 peter": "1 Peter",
  "1peter": "1 Peter",
  "1pet": "1 Peter",
  "1pe": "1 Peter",
  "1pt": "1 Peter",
  "i peter": "1 Peter",
  "1 pet": "1 Peter",
  // 2 Peter
  "2 peter": "2 Peter",
  "2peter": "2 Peter",
  "2pet": "2 Peter",
  "2pe": "2 Peter",
  "2pt": "2 Peter",
  "ii peter": "2 Peter",
  "2 pet": "2 Peter",
  // 1 John
  "1 john": "1 John",
  "1john": "1 John",
  "1joh": "1 John",
  "1jn": "1 John",
  "1jo": "1 John",
  "i john": "1 John",
  // 2 John
  "2 john": "2 John",
  "2john": "2 John",
  "2joh": "2 John",
  "2jn": "2 John",
  "ii john": "2 John",
  // 3 John
  "3 john": "3 John",
  "3john": "3 John",
  "3joh": "3 John",
  "3jn": "3 John",
  "iii john": "3 John",
  // Jude
  jude: "Jude",
  jud: "Jude",
  // Revelation
  revelation: "Revelation",
  rev: "Revelation",
  re: "Revelation",
  rv: "Revelation"
};
function normaliseBook(raw) {
  var _a;
  const key = raw.trim().toLowerCase().replace(/\s+/g, " ");
  return (_a = BOOK_MAP[key]) != null ? _a : null;
}
var SCRIPTURE_REGEX = /\b((?:[123]\s?)?[A-Z][a-z]+(?:\s[A-Z][a-z]+)?)\s+(\d+):(\d+)(?:-(\d+))?/g;
function parseReferences(text) {
  const results = [];
  SCRIPTURE_REGEX.lastIndex = 0;
  let m;
  while ((m = SCRIPTURE_REGEX.exec(text)) !== null) {
    const rawBook = m[1];
    const book = normaliseBook(rawBook);
    if (!book)
      continue;
    const chapter = parseInt(m[2], 10);
    const verseStart = parseInt(m[3], 10);
    const verseEnd = m[4] ? parseInt(m[4], 10) : verseStart;
    results.push({
      raw: m[0],
      book,
      chapter,
      verseStart,
      verseEnd,
      crossChapter: false,
      index: m.index,
      length: m[0].length
    });
  }
  return results;
}
var verseCache = /* @__PURE__ */ new Map();
var CHAPTER_PREFIX = {
  "Genesis": "Gen",
  "Exodus": "Exod",
  "Leviticus": "Lev",
  "Numbers": "Num",
  "Deuteronomy": "Deut",
  "Joshua": "Josh",
  "Judges": "Judg",
  "Ruth": "Ruth",
  "1 Samuel": "1 Sam",
  "2 Samuel": "2 Sam",
  "1 Kings": "1 Kgs",
  "2 Kings": "2 Kgs",
  "1 Chronicles": "1 Chr",
  "2 Chronicles": "2 Chr",
  "Ezra": "Ezr",
  "Nehemiah": "Neh",
  "Esther": "Esth",
  "Job": "Job",
  "Psalms": "Ps",
  "Proverbs": "Prov",
  "Ecclesiastes": "Eccl",
  "Song of Solomon": "Song",
  "Isaiah": "Isa",
  "Jeremiah": "Jer",
  "Lamentations": "Lam",
  "Ezekiel": "Ezek",
  "Daniel": "Dan",
  "Hosea": "Hos",
  "Joel": "Joel",
  "Amos": "Amos",
  "Obadiah": "Obad",
  "Jonah": "Jonah",
  "Micah": "Mic",
  "Nahum": "Nah",
  "Habakkuk": "Hab",
  "Zephaniah": "Zeph",
  "Haggai": "Hag",
  "Zechariah": "Zech",
  "Malachi": "Mal",
  "Matthew": "Matt",
  "Mark": "Mark",
  "Luke": "Luke",
  "John": "John",
  "Acts": "Acts",
  "Romans": "Rom",
  "1 Corinthians": "1 Cor",
  "2 Corinthians": "2 Cor",
  "Galatians": "Gal",
  "Ephesians": "Eph",
  "Philippians": "Phil",
  "Colossians": "Col",
  "1 Thessalonians": "1 Thess",
  "2 Thessalonians": "2 Thess",
  "1 Timothy": "1 Tim",
  "2 Timothy": "2 Tim",
  "Titus": "Titus",
  "Philemon": "Phlm",
  "Hebrews": "Heb",
  "James": "Jas",
  "1 Peter": "1 Pet",
  "2 Peter": "2 Pet",
  "1 John": "1 John",
  "2 John": "2 John",
  "3 John": "3 John",
  "Jude": "Jude",
  "Revelation": "Rev"
};
function chapterPath(csbFolder, book, chapter) {
  var _a;
  const prefix = (_a = CHAPTER_PREFIX[book]) != null ? _a : book;
  return `${csbFolder}/${book}/${prefix} ${chapter}.md`;
}
function parseChapterFile(content) {
  const map = /* @__PURE__ */ new Map();
  const lines = content.split(/\r?\n/);
  let currentVerse = null;
  let currentLines = [];
  const flush = () => {
    if (currentVerse !== null) {
      map.set(currentVerse, currentLines.join(" ").replace(/\s+/g, " ").trim());
    }
  };
  for (const line of lines) {
    const headingMatch = line.match(/^#{6}\s+(\d+)\s*$/);
    if (headingMatch) {
      flush();
      currentVerse = parseInt(headingMatch[1], 10);
      currentLines = [];
    } else if (currentVerse !== null) {
      if (/^#{1,5}\s/.test(line)) {
        flush();
        currentVerse = null;
        currentLines = [];
      } else if (line.trim().length > 0) {
        const stripped = line.replace(/\s*#{2,5}\s+[^#\n]+/g, "").trim();
        if (stripped.length > 0) {
          currentLines.push(stripped);
        }
      }
    }
  }
  flush();
  return map;
}
async function loadChapter(app, csbFolder, book, chapter) {
  const path = chapterPath(csbFolder, book, chapter);
  if (verseCache.has(path)) {
    return verseCache.get(path);
  }
  const file = app.vault.getAbstractFileByPath(path);
  if (!file || !(file instanceof import_obsidian.TFile))
    return null;
  const content = await app.vault.read(file);
  const map = parseChapterFile(content);
  verseCache.set(path, map);
  return map;
}
async function fetchVerses(app, csbFolder, ref) {
  if (ref.crossChapter) {
    throw new Error("Cross-chapter ranges not supported yet.");
  }
  const map = await loadChapter(app, csbFolder, ref.book, ref.chapter);
  if (!map) {
    throw new Error(`Passage not found: ${ref.raw}`);
  }
  const results = [];
  for (let v = ref.verseStart; v <= ref.verseEnd; v++) {
    const text = map.get(v);
    if (text === void 0) {
      throw new Error(`Passage not found: ${ref.raw}`);
    }
    results.push({ verse: v, text });
  }
  return results;
}
var ScriptureExpander = class {
  constructor(app, csbFolder, component, sourcePath) {
    /** Track which refs are currently expanded: span element -> expanded div. */
    this.expanded = /* @__PURE__ */ new Map();
    this.app = app;
    this.csbFolder = csbFolder;
    this.component = component;
    this.sourcePath = sourcePath;
  }
  updateFolder(csbFolder) {
    this.csbFolder = csbFolder;
  }
  updateSourcePath(sourcePath) {
    this.sourcePath = sourcePath;
  }
  /**
   * Walk the rendered DOM, find text nodes outside special blocks,
   * and wrap detected scripture references in tappable spans.
   */
  processElement(root) {
    this.walkNode(root);
  }
  walkNode(node) {
    var _a, _b;
    if (node.nodeType === Node.ELEMENT_NODE) {
      const el = node;
      const tag = el.tagName.toLowerCase();
      if (tag === "pre" || tag === "code" || el.classList.contains("preach-scripture-ref") || el.classList.contains("preach-scripture-expand")) {
        return;
      }
    }
    if (node.nodeType === Node.TEXT_NODE) {
      const text = (_a = node.textContent) != null ? _a : "";
      const refs = parseReferences(text);
      if (refs.length === 0)
        return;
      const frag = document.createDocumentFragment();
      let cursor = 0;
      for (const ref of refs) {
        if (ref.index > cursor) {
          frag.appendChild(document.createTextNode(text.slice(cursor, ref.index)));
        }
        const span = document.createElement("span");
        span.className = "preach-scripture-ref";
        span.textContent = ref.raw;
        span.dataset.ref = JSON.stringify({
          raw: ref.raw,
          book: ref.book,
          chapter: ref.chapter,
          verseStart: ref.verseStart,
          verseEnd: ref.verseEnd,
          crossChapter: ref.crossChapter
        });
        span.addEventListener("pointerdown", (e) => {
          e.stopPropagation();
          void this.handleTap(span, ref);
        });
        frag.appendChild(span);
        cursor = ref.index + ref.length;
      }
      if (cursor < text.length) {
        frag.appendChild(document.createTextNode(text.slice(cursor)));
      }
      (_b = node.parentNode) == null ? void 0 : _b.replaceChild(frag, node);
      return;
    }
    const children = Array.from(node.childNodes);
    for (const child of children) {
      this.walkNode(child);
    }
  }
  async handleTap(span, ref) {
    const existing = this.expanded.get(span);
    if (existing) {
      existing.remove();
      this.expanded.delete(span);
      span.classList.remove("preach-scripture-ref--open");
      return;
    }
    this.expanded.forEach((el, s) => {
      el.remove();
      s.classList.remove("preach-scripture-ref--open");
    });
    this.expanded.clear();
    const expandEl = document.createElement("span");
    expandEl.className = "preach-scripture-expand";
    expandEl.textContent = "Loading...";
    span.insertAdjacentElement("afterend", expandEl);
    this.expanded.set(span, expandEl);
    span.classList.add("preach-scripture-ref--open");
    try {
      const verses = await fetchVerses(this.app, this.csbFolder, ref);
      expandEl.empty();
      expandEl.className = "preach-scripture-expand";
      const passageEl = expandEl.createEl("span", { cls: "preach-scripture-passage" });
      for (const { verse, text } of verses) {
        passageEl.createEl("sup", { cls: "preach-scripture-verse-num", text: String(verse) });
        const tmp = document.createElement("div");
        await import_obsidian.MarkdownRenderer.render(this.app, text, tmp, this.sourcePath, this.component);
        const nodes = Array.from(tmp.childNodes);
        for (const node of nodes) {
          if (node.nodeType === Node.ELEMENT_NODE && node.tagName === "P") {
            const children = Array.from(node.childNodes);
            for (const child of children) {
              passageEl.appendChild(child);
            }
          } else {
            passageEl.appendChild(node);
          }
        }
        passageEl.appendChild(document.createTextNode(" "));
      }
      expandEl.addEventListener("pointerdown", (e) => {
        e.stopPropagation();
        expandEl.remove();
        this.expanded.delete(span);
        span.classList.remove("preach-scripture-ref--open");
      });
    } catch (err) {
      expandEl.empty();
      expandEl.className = "preach-scripture-expand preach-scripture-expand--error";
      const msg = err instanceof Error ? err.message : `Could not load ${ref.raw}`;
      expandEl.createEl("span", { cls: "preach-scripture-error-text", text: msg });
      expandEl.addEventListener("pointerdown", (e) => {
        e.stopPropagation();
        expandEl.remove();
        this.expanded.delete(span);
        span.classList.remove("preach-scripture-ref--open");
      });
    }
  }
  /** Collapse all expanded passages (call when view re-renders). */
  collapseAll() {
    this.expanded.forEach((el) => el.remove());
    this.expanded.clear();
  }
};

// src/preach-view.ts
var PREACH_VIEW_TYPE = "preach-md-view";
function extractHeadings(markdown, level) {
  const prefix = "#".repeat(level) + " ";
  const results = [];
  for (const line of markdown.split("\n")) {
    if (line.startsWith(prefix)) {
      const text = line.slice(prefix.length).trim();
      const slug = text.toLowerCase().replace(/[^\w\s-]/g, "").replace(/\s+/g, "-");
      results.push({ text, slug });
    }
  }
  return results;
}
var PreachView = class extends import_obsidian2.ItemView {
  constructor(leaf, plugin) {
    super(leaf);
    this.file = null;
    // Persisted scroll position within this session
    this.savedScrollTop = 0;
    // Wake lock
    this.wakeLock = null;
    // Edge-swipe suppression
    this.touchHandler = null;
    // Exit confirm state
    this.exitConfirming = false;
    this.exitConfirmTimeout = null;
    // View header (hidden while preach mode is active)
    this.viewHeaderEl = null;
    this.plugin = plugin;
  }
  getViewType() {
    return PREACH_VIEW_TYPE;
  }
  getDisplayText() {
    return this.file ? this.file.basename : "Preach";
  }
  getIcon() {
    return "book-open";
  }
  async onOpen() {
    const leafContent = this.containerEl.closest(".workspace-leaf-content");
    if (leafContent) {
      this.viewHeaderEl = leafContent.querySelector(".view-header");
      if (this.viewHeaderEl)
        this.viewHeaderEl.classList.add("preach-view-header--hidden");
    }
    this.renderComponent = new import_obsidian2.Component();
    this.renderComponent.load();
    this.highlightManager = new HighlightManager(
      this.app,
      this.file,
      this.renderComponent
    );
    this.scriptureExpander = new ScriptureExpander(
      this.app,
      this.plugin.settings.csbFolderPath,
      this.renderComponent,
      ""
    );
    this.buildUI();
    await this.requestWakeLock();
    this.suppressEdgeSwipes();
    if (this.file) {
      await this.renderFile(this.file);
    }
    this.timer.start();
  }
  async onClose() {
    if (this.viewHeaderEl) {
      this.viewHeaderEl.classList.remove("preach-view-header--hidden");
      this.viewHeaderEl = null;
    }
    this.timer.stop();
    await this.releaseWakeLock();
    this.restoreEdgeSwipes();
    this.renderComponent.unload();
  }
  async setFile(file) {
    this.file = file;
    if (this.highlightManager) {
      this.highlightManager.updateFile(file);
    }
    if (this.scrollEl) {
      await this.renderFile(file);
    }
  }
  // Build the full preach UI into containerEl
  buildUI() {
    const root = this.containerEl;
    root.empty();
    root.addClass("preach-md-root");
    this.scrollEl = root.createEl("div", { cls: "preach-content" });
    this.scrollEl.addEventListener("scroll", () => {
      this.savedScrollTop = this.scrollEl.scrollTop;
    });
    this.timerEl = root.createEl("div", { cls: "preach-timer-wrap" });
    this.timer = new PreachTimer(this.timerEl, {
      targetMinutes: this.plugin.settings.targetMinutes,
      warnMinutes: this.plugin.settings.warnMinutes,
      critMinutes: this.plugin.settings.critMinutes
    });
    const corners = root.createEl("div", { cls: "preach-corners" });
    this.outlineBtn = corners.createEl("button", {
      cls: "preach-corner preach-corner--top-left",
      attr: { "aria-label": "Outline", title: "Outline" }
    });
    const outlineSvg = this.outlineBtn.createSvg("svg", {
      attr: { xmlns: "http://www.w3.org/2000/svg", width: "22", height: "22", viewBox: "0 0 24 24", fill: "none", stroke: "currentColor", "stroke-width": "2", "stroke-linecap": "round", "stroke-linejoin": "round" }
    });
    outlineSvg.createSvg("line", { attr: { x1: "3", y1: "6", x2: "21", y2: "6" } });
    outlineSvg.createSvg("line", { attr: { x1: "3", y1: "12", x2: "15", y2: "12" } });
    outlineSvg.createSvg("line", { attr: { x1: "3", y1: "18", x2: "18", y2: "18" } });
    this.outlineBtn.addEventListener("pointerdown", (e) => {
      e.stopPropagation();
      this.toggleOutline();
    });
    const exitWrap = corners.createEl("div", {
      cls: "preach-corner-wrap preach-corner-wrap--top-right"
    });
    this.exitChip = exitWrap.createEl("span", {
      cls: "preach-exit-chip",
      text: "Exit?"
    });
    this.exitBtn = exitWrap.createEl("button", {
      cls: "preach-corner preach-corner--top-right",
      attr: { "aria-label": "Exit preach mode", title: "Exit" }
    });
    const exitSvg = this.exitBtn.createSvg("svg", {
      attr: { xmlns: "http://www.w3.org/2000/svg", width: "22", height: "22", viewBox: "0 0 24 24", fill: "none", stroke: "currentColor", "stroke-width": "2", "stroke-linecap": "round", "stroke-linejoin": "round" }
    });
    exitSvg.createSvg("line", { attr: { x1: "18", y1: "6", x2: "6", y2: "18" } });
    exitSvg.createSvg("line", { attr: { x1: "6", y1: "6", x2: "18", y2: "18" } });
    this.exitBtn.addEventListener("pointerdown", (e) => {
      e.stopPropagation();
      this.handleExit();
    });
    this.editBtn = corners.createEl("button", {
      cls: "preach-corner preach-corner--bottom-right",
      attr: { "aria-label": "Edit note", title: "Edit" }
    });
    const editSvg = this.editBtn.createSvg("svg", {
      attr: { xmlns: "http://www.w3.org/2000/svg", width: "22", height: "22", viewBox: "0 0 24 24", fill: "none", stroke: "currentColor", "stroke-width": "2", "stroke-linecap": "round", "stroke-linejoin": "round" }
    });
    editSvg.createSvg("path", { attr: { d: "M11 4H4a2 2 0 0 0-2 2v14a2 2 0 0 0 2 2h14a2 2 0 0 0 2-2v-7" } });
    editSvg.createSvg("path", { attr: { d: "M18.5 2.5a2.121 2.121 0 0 1 3 3L12 15l-4 1 1-4 9.5-9.5z" } });
    this.editBtn.addEventListener("pointerdown", (e) => {
      e.stopPropagation();
      this.goToEdit();
    });
    this.highlightManager.init(null, this.scrollEl, this.scrollEl);
    this.overlayEl = root.createEl("div", {
      cls: "preach-outline-overlay preach-outline-overlay--hidden"
    });
    this.overlayEl.addEventListener("pointerdown", (e) => {
      if (e.target === this.overlayEl) {
        this.closeOutline();
      }
    });
  }
  // Render the file into the scroll area using block-by-block rendering
  async renderFile(file) {
    const scrollTop = this.savedScrollTop;
    this.scriptureExpander.collapseAll();
    this.scrollEl.empty();
    const markdown = await this.app.vault.read(file);
    const blocks = parseBlocks(markdown);
    this.highlightManager.attachBlocks(blocks);
    const body = this.scrollEl.createEl("div", { cls: "preach-body" });
    for (let i = 0; i < blocks.length; i++) {
      const block = blocks[i];
      const wrapper = body.createEl("div", {
        cls: "preach-block",
        attr: {
          "data-block-index": String(i),
          "data-highlightable": block.highlightable ? "true" : "false"
        }
      });
      await import_obsidian2.MarkdownRenderer.render(
        this.app,
        block.content,
        wrapper,
        file.path,
        this.renderComponent
      );
      if (block.highlightable) {
        wrapper.addEventListener("pointerdown", (e) => {
          const target = e.target;
          if (target.closest(".preach-scripture-ref") || target.closest(".preach-scripture-expand")) {
            return;
          }
          if (this.highlightManager.isActive()) {
            e.stopPropagation();
            void this.highlightManager.handleBlockTap(i).then(() => {
              void this.renderFile(file);
            });
          }
        });
      }
    }
    this.scriptureExpander.updateSourcePath(file.path);
    this.scriptureExpander.processElement(body);
    this.tagRenderedHeadings(body, markdown);
    window.requestAnimationFrame(() => {
      this.scrollEl.scrollTop = scrollTop;
    });
  }
  /**
   * Attach data-preach-slug to rendered heading elements so the outline
   * can call scrollIntoView on them by reference.
   */
  tagRenderedHeadings(wrapper, markdown) {
    const level = this.plugin.settings.sectionHeadingLevel;
    const headings = extractHeadings(markdown, level);
    const tag = `h${level}`;
    const rendered = wrapper.querySelectorAll(tag);
    rendered.forEach((el, i) => {
      if (headings[i]) {
        el.dataset.preachSlug = headings[i].slug;
      }
    });
  }
  // Outline overlay controls
  toggleOutline() {
    if (!this.overlayEl.classList.contains("preach-outline-overlay--hidden")) {
      this.closeOutline();
      return;
    }
    this.openOutline();
  }
  openOutline() {
    var _a;
    if (!this.file)
      return;
    const panel = (_a = this.overlayEl.querySelector(".preach-outline-panel")) != null ? _a : this.overlayEl.createEl("div", { cls: "preach-outline-panel" });
    panel.empty();
    const level = this.plugin.settings.sectionHeadingLevel;
    const tag = `h${level}`;
    const headingEls = this.scrollEl.querySelectorAll(tag);
    if (headingEls.length === 0) {
      panel.createEl("p", {
        cls: "preach-outline-empty",
        text: "No sections found."
      });
    } else {
      headingEls.forEach((el) => {
        var _a2;
        const btn = panel.createEl("button", {
          cls: "preach-outline-item",
          text: (_a2 = el.textContent) != null ? _a2 : ""
        });
        btn.addEventListener("pointerdown", (e) => {
          e.stopPropagation();
          el.scrollIntoView({ behavior: "smooth", block: "start" });
          this.closeOutline();
        });
      });
    }
    this.overlayEl.classList.remove("preach-outline-overlay--hidden");
  }
  closeOutline() {
    this.overlayEl.classList.add("preach-outline-overlay--hidden");
  }
  // Exit two-step confirmation
  handleExit() {
    if (this.exitConfirming) {
      this.confirmExit();
      return;
    }
    this.exitConfirming = true;
    this.exitChip.classList.add("preach-exit-chip--visible");
    this.exitConfirmTimeout = window.setTimeout(() => {
      this.exitConfirming = false;
      this.exitChip.classList.remove("preach-exit-chip--visible");
      this.exitConfirmTimeout = null;
    }, 3e3);
  }
  confirmExit() {
    if (this.exitConfirmTimeout !== null) {
      window.clearTimeout(this.exitConfirmTimeout);
      this.exitConfirmTimeout = null;
    }
    this.exitConfirming = false;
    this.exitChip.classList.remove("preach-exit-chip--visible");
    this.leaf.detach();
  }
  // Edit round-trip: open the file in an edit leaf, preserving scroll
  goToEdit() {
    if (!this.file)
      return;
    this.savedScrollTop = this.scrollEl.scrollTop;
    const existingLeaf = this.app.workspace.getLeavesOfType("markdown").find(
      (l) => {
        var _a, _b;
        return ((_a = l.view.file) == null ? void 0 : _a.path) === ((_b = this.file) == null ? void 0 : _b.path);
      }
    );
    if (existingLeaf) {
      this.app.workspace.setActiveLeaf(existingLeaf, { focus: true });
    } else {
      const leaf = this.app.workspace.getLeaf(false);
      if (this.file) {
        void leaf.openFile(this.file, { active: true });
      }
    }
  }
  // Screen wake lock
  async requestWakeLock() {
    try {
      if ("wakeLock" in navigator) {
        const nav = navigator;
        this.wakeLock = await nav.wakeLock.request("screen");
      }
    } catch (e) {
    }
  }
  async releaseWakeLock() {
    try {
      if (this.wakeLock) {
        await this.wakeLock.release();
        this.wakeLock = null;
      }
    } catch (e) {
    }
  }
  // Suppress edge-swipe gestures (Obsidian Mobile sidebar open)
  suppressEdgeSwipes() {
    this.touchHandler = (e) => {
      if (e.touches.length === 1) {
        const x = e.touches[0].clientX;
        if (x < 30 || x > window.innerWidth - 30) {
          e.stopPropagation();
        }
      }
    };
    document.addEventListener("touchstart", this.touchHandler, {
      capture: true,
      passive: true
    });
  }
  restoreEdgeSwipes() {
    if (this.touchHandler) {
      document.removeEventListener("touchstart", this.touchHandler, {
        capture: true
      });
      this.touchHandler = null;
    }
  }
};

// src/settings.ts
var import_obsidian3 = require("obsidian");
var DEFAULT_SETTINGS = {
  targetMinutes: 30,
  warnMinutes: 5,
  critMinutes: 1,
  sectionHeadingLevel: 2,
  csbFolderPath: "30_Knowledge/Theology/Bible/CSB"
};
var PreachMDSettingTab = class extends import_obsidian3.PluginSettingTab {
  constructor(app, plugin) {
    super(app, plugin);
    this.plugin = plugin;
  }
  display() {
    const { containerEl } = this;
    containerEl.empty();
    new import_obsidian3.Setting(containerEl).setName("Timer").setHeading();
    new import_obsidian3.Setting(containerEl).setName("Target duration (minutes)").setDesc("The countdown starts from this value.").addText(
      (text) => text.setPlaceholder("30").setValue(String(this.plugin.settings.targetMinutes)).onChange((value) => {
        const n = parseInt(value, 10);
        if (!isNaN(n) && n > 0) {
          this.plugin.settings.targetMinutes = n;
          void this.plugin.saveSettings();
        }
      })
    );
    new import_obsidian3.Setting(containerEl).setName("Amber warning (minutes remaining)").setDesc("Timer turns amber when this many minutes remain.").addText(
      (text) => text.setPlaceholder("5").setValue(String(this.plugin.settings.warnMinutes)).onChange((value) => {
        const n = parseInt(value, 10);
        if (!isNaN(n) && n > 0) {
          this.plugin.settings.warnMinutes = n;
          void this.plugin.saveSettings();
        }
      })
    );
    new import_obsidian3.Setting(containerEl).setName("Red warning (minutes remaining)").setDesc("Timer turns red when this many minutes remain.").addText(
      (text) => text.setPlaceholder("1").setValue(String(this.plugin.settings.critMinutes)).onChange((value) => {
        const n = parseInt(value, 10);
        if (!isNaN(n) && n > 0) {
          this.plugin.settings.critMinutes = n;
          void this.plugin.saveSettings();
        }
      })
    );
    new import_obsidian3.Setting(containerEl).setName("Navigation").setHeading();
    new import_obsidian3.Setting(containerEl).setName("Section heading level").setDesc(
      "Heading level used to build the outline (2 = ##, 3 = ###)."
    ).addText(
      (text) => text.setPlaceholder("2").setValue(String(this.plugin.settings.sectionHeadingLevel)).onChange((value) => {
        const n = parseInt(value, 10);
        if (!isNaN(n) && n >= 1 && n <= 6) {
          this.plugin.settings.sectionHeadingLevel = n;
          void this.plugin.saveSettings();
        }
      })
    );
    new import_obsidian3.Setting(containerEl).setName("Scripture").setHeading();
    new import_obsidian3.Setting(containerEl).setName("Bible folder path").setDesc(
      "Vault path to your bible chapter files. Each book is a subfolder; each chapter is a separate .md file."
    ).addText(
      (text) => text.setPlaceholder("30_Knowledge/Theology/Bible/CSB").setValue(this.plugin.settings.csbFolderPath).onChange((value) => {
        this.plugin.settings.csbFolderPath = value.trim();
        void this.plugin.saveSettings();
      })
    );
  }
};

// src/main.ts
var PreachMDPlugin = class extends import_obsidian4.Plugin {
  async onload() {
    await this.loadSettings();
    this.registerView(
      PREACH_VIEW_TYPE,
      (leaf) => new PreachView(leaf, this)
    );
    this.addCommand({
      id: "open-preach-mode",
      name: "Open preach mode",
      callback: () => this.openPreachMode()
    });
    this.addRibbonIcon("book-open", "Open preach mode", () => {
      void this.openPreachMode();
    });
    this.addSettingTab(new PreachMDSettingTab(this.app, this));
  }
  onunload() {
  }
  async loadSettings() {
    this.settings = Object.assign({}, DEFAULT_SETTINGS, await this.loadData());
  }
  async saveSettings() {
    await this.saveData(this.settings);
  }
  async openPreachMode() {
    var _a;
    const activeFile = this.app.workspace.getActiveFile();
    if (!activeFile) {
      return;
    }
    const existingLeaves = this.app.workspace.getLeavesOfType(PREACH_VIEW_TYPE);
    for (const leaf2 of existingLeaves) {
      const view2 = leaf2.view;
      if (((_a = view2.file) == null ? void 0 : _a.path) === activeFile.path) {
        this.app.workspace.setActiveLeaf(leaf2, { focus: true });
        return;
      }
    }
    const leaf = this.app.workspace.getLeaf("tab");
    await leaf.setViewState({
      type: PREACH_VIEW_TYPE,
      active: true
    });
    const view = leaf.view;
    await view.setFile(activeFile);
    this.app.workspace.setActiveLeaf(leaf, { focus: true });
  }
};
